import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { AuthProvider, useAuth } from "@/contexts/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `${process.env.COLLEGE_NAME} - Management System`,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
